#!/usr/bin/env bash


usage() {
  echo "Usage: $(basename $0) [-t threads] -i bwaIndex fastq1 [fastq2 ... fastqN ]" 1>&2
  echo "" 1>&2
  echo "  bwaIndex can be a path to a bwa index prefix or a tarball of an bwa index" 1>&2
  echo "" 1>&2
  exit 1
}

################################
### PARSE COMMAND LINE ARGS ####
################################

while getopts ":i:t:" opt; do
  case $opt in
  t)
   NTHREADS=$OPTARG
   ;;
  i)
   INDEXFILE=$OPTARG
   ;;
  \?)
   echo "Invalid option: -$OPTARG" >&2
   usage
   ;;
  [?])
   usage
   ;;
  :)
   echo "Option -$OPTARG requires an argument." >&2
   echo "" >&2
   usage
   ;;
  esac
done

shift $((OPTIND-1))

if [ -z $NTHREADS ]; then
  NTHREADS=1
fi

if [[ -z $INDEXFILE ]]; then
  echo "must define an bwa index with -i"
fi

if [[ $# -eq 0 ]] ; then
  echo 'no fastq files specified'
  exit 1
fi

INPUT=$@

align(){

  INPUT=$1
  INDEXFILE=$2
  NTHREADS=$3
  
  for f in $INPUT; do
   
   ISPAIRED=$(head -n 8 $INPUT | paste - - - - | awk '{print $1}' | uniq -c | awk '{print $1}' | head -n 1)
   if [[ $ISPAIRED -eq 2 ]]; then
     PAIRARG="-p"
     echo "fastq is interleaved, treating as paired-end"
   else
     PAIRARG=""
     echo "fastq is not interleaved, treating as single-end"
   fi
   
   # check if file exists
   if [[ ! -f $f ]]; then echo "fastq file \"$f\" not found"; exit 1; fi
   # check input is a fastq
   if [[ $f != *.fastq ]] && [[ $f != *.fq ]]; then echo "input is not an uncompressed fastq"; exit 1; fi
   
   BASE="$(basename $f | sed 's/\.fq$//g' | sed 's/\.fastq$//g')"
   OUTPUT=${BASE}.bam
   LOGFILE=${OUTPUT}.log
   
   bwa mem $PAIRARG -v 2 -t $NTHREADS $INDEXFILE $f | samtools view -Shb - 2> ${OUTPUT}.log > $OUTPUT
   echo $OUTPUT
  done 
}

export -f align

parallel --will-cite -k -j 1 "align {} $INDEXFILE $NTHREADS" ::: $INPUT
