#!/usr/bin/env bash

usage() {
  echo "Usage: $(basename $0) [-t threads ] fastq1 [fastq2 ... fastqN ]" 1>&2
  echo "" 1>&2
  exit 1
}

while getopts ":t:" opt; do
  case $opt in
  t)
    NTHREADS=$OPTARG
   ;;
  \?)
   echo "Invalid option: -$OPTARG" >&2
   usage
   ;;
  [?])
   usage
   ;;
  :)
   echo "Option -$OPTARG requires an argument." >&2
   echo "" >&2
   usage
   ;;
  esac
done

if [ -z $NTHREADS ]; then
  NTHREADS=1
fi

shift $((OPTIND-1))

if [[ $# -eq 0 ]] ; then
  echo 'no fastq files specified'
  exit 1
fi

INPUT=$@

clip(){
  INPUT=$1
  for f in $INPUT; do
   # check if file exists
   if [[ ! -f $f ]]; then echo "fastq file \"$f\" not found"; exit 1; fi
   # check input is a fastq
   if [[ $f != *.fastq ]] && [[ $f != *.fq ]] && [[ $f != *.gz ]]; then echo "input is not a fastq"; exit 1; fi
   
   BASE="$(basename $f | sed 's/\.gz$//g' | sed 's/\.fq$//g' | sed 's/\.fastq$//g')"
   OUTPUT=${BASE}_clip.fastq
   LOGFILE=${OUTPUT}.log
   
   cutadapt -a AGATCGGAAGAGCACACGTCTG -q 0 -O 1 -m 0 -o $OUTPUT $f > $LOGFILE
   echo $OUTPUT
  done 
}

export -f clip

parallel --will-cite -k -j $NTHREADS "clip {}" ::: $INPUT
