#!/usr/bin/env bash

FASTA=$1
OUTPUT="${FASTA%.*}.chrom.sizes"

awk '{
  if($0~">"){
    if(length(chrom)!=0){
      print chrom,clen
    }
    chrom=$1;
    clen=0
  } else{
    clen+=length($0)
  }
} END{
  print chrom,clen
}' OFS='\t' $FASTA | tr -d '>' | sort -m -k1,1 > $OUTPUT
    
echo $OUTPUT
