#!/usr/bin/env bash

usage() {
  echo "Usage: $(basename $0) [-t threads ] -r reference.bg bedGraph1 [bedGraph2 bedGraphN ]" 1>&2
  echo "" 1>&2
  exit 1
}

while getopts ":r:t:" opt; do
  case $opt in
 r)
    REFERENCE=$OPTARG
   ;;
 t)
    NUMTHREADS=$OPTARG
   ;;
 \?)
   echo "Invalid option: -$OPTARG" >&2
   usage
   ;;
  [?])
   usage
   ;;
  :)
   echo "Option -$OPTARG requires an argument." >&2
   echo "" >&2
   usage
   ;;
  esac
done

if [ -z $NTHREADS ]; then
  if [ -z $NUMTHREADS ]; then
    NTHREADS=1
  else
    NTHREADS=$NUMTHREADS
  fi
fi

shift $((OPTIND-1))

if [[ -z $@ ]]; then
  INPUT=$(cat /dev/stdin)
else
  INPUT=$@
fi

for i in $INPUT; do
  if [[ ! -f $i ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi
  if [[ $i != *.bg ]]; then >&2 echo "file \"$i\" is not a bedGraph file"; exit 1; fi
done

iqrn(){
  BG=$1
  BASE="$(basename $BG | sed 's/\.bg$//g')"
  OUTPUT="${BASE}_inorm.bg"
  
  NUMLINES=$(cat $BG | wc -l)
  Q1=$(echo $NUMLINES/4 | bc)
  Q2=$(echo $NUMLINES/2 | bc)
  Q3=$(echo 3*$NUMLINES/4 | bc)
  ST=$(sort -k4,4n $BG | \
    awk -v q1=$Q1 -v q2=$Q2 -v q3=$Q3 '{if(NR==q1){Q1=$4};if(NR==q2){Q2=$4};if(NR==q3){Q3=$4}}END{print Q3-Q1,Q2}')
  REFIQR=5.5
  IQR=$(echo $ST | cut -d ' ' -f 1)
  MDN=$(echo $ST | cut -d ' ' -f 2)
  awk -v refiqr=$REFIQR -v mdn=$MDN -v iqr=$IQR 'BEGIN{scalar=refiqr/iqr} {print $1,$2,$3,($4-mdn)*scalar}' OFS='\t' $BG > $OUTPUT
  echo $OUTPUT
}

normalize(){
  BG=$1
  RF=$2
  
  BASE="$(basename $BG | sed 's/\.bg$//g')"
  OUTPUT="${BASE}_qnorm.bg"
  BGLINES=$(cat $BG | wc -l)
  RFLINES=$(cat $RF | wc -l)
  TMPREFN="$(mktemp).bg"
  
  if [[ $BGLINES -gt $RFLINES ]]; then
    COPYNUM=$((1+BGLINES/RFLINES))
    cat $(yes "$RF" | head -n $COPYNUM) > $TMPREFN
    RF=$TMPREFN
  fi
  
  paste <(sort -T . -k4,4g $BG) <(shuf -n $BGLINES $RF | sort -k4,4g) | \
    cut -f 1,2,3,8 | sort -k1,1 -k2,2n > $OUTPUT
  
  #rm -f $TMPREFN
  
  echo $OUTPUT
}

export -f iqrn
export -f normalize

if [[ ! -f $REFERENCE ]]; then
  >&2 echo "reference file not found, making an average distribution after IQR-normalizing input bedGraphs"
  INPUTI=$(parallel --no-notice -k -j $NTHREADS "iqrn {}" ::: $INPUT)
  echo $INPUTI
  tmprefi="$(mktemp).bg"
  cat $INPUTI > $tmprefi
  REFERENCE=$tmprefi
  >&2 echo "reference is $REFERENCE"
else
  if [[ $REFERENCE != *.bg ]]; then
    >&2 echo "file \"$REFERENCE\" is not a bedGraph file"
    exit 1
  fi
fi

parallel --no-notice -k -j $NTHREADS "normalize {} $REFERENCE" ::: $INPUT

#rm -f tmprefi
