#!/bin/bash

usage() {
  echo "Usage: $(basename $0) [-t threads] -i bwaIndex fastq1 [fastq2 ... fastqN ]" 1>&2
  echo "" 1>&2
  echo "  bwaIndex can be a path to a bwa index prefix or a tarball of an bwa index" 1>&2
  echo "" 1>&2
  exit 1
}

################################
### PARSE COMMAND LINE ARGS ####
################################

while getopts ":i:t:g:p" opt; do
  case $opt in
  e)
   EARLYBGS=$OPTARG
   ;;
  l)
   LATEBGS=$OPTARG
   ;;
  p)
   PAIRED=1
   ;;
  t)
   NTHREADS=$OPTARG
   ;;
  w)
   WINDOWSIZE=$OPTARG
   ;;
  i)
   INDEXFILE=$OPTARG
   ;;
  m)
   MEMPERTHREAD=$OPTARG
   ;;
  \?)
   echo "Invalid option: -$OPTARG" >&2
   usage
   ;;
  [?])
   usage
   ;;
  :)
   echo "Option -$OPTARG requires an argument." >&2
   echo "" >&2
   usage
   ;;
  esac
done

shift $((OPTIND-1))


if [ -z $NTHREADS ]; then
  NTHREADS=1
fi

if [[ -z $WINDOWSIZE ]]; then
  WINDOWSIZE=5000
fi

if [[ -z $MEMPERTHREAD ]]; then
  MEMPERTHREAD=5G
fi

if [[ -z $INDEXFILE ]]; then
  echo "must define an fasta or bwa index with -i"
fi

if [[ $# -eq 0 ]] ; then
  echo 'no fastq files specified'
  exit 1
fi

#check that dependencies are in PATH and correct versions
#check if chromsizes or fasta specified with -g
#check input files

if [[ -z $PAIRED ]]; then
  #todo: make sure length of EARLYBGS and LATEBGS is even
  #todo: check to see if read names in r1 and r2 are identical
  ER1=$(echo $ER1 | tr ' ' ',')
  ER2=$(echo $ER2 | tr ' ' ',')
  LR1=$(echo $LR1 | tr ' ' ',')
  LR2=$(echo $LR2 | tr ' ' ',')
  E=$(interleave -t $NTHREADS $ER1 $ER2)
  L=$(interleave -t $NTHREADS $LR1 $LR2)
else
  E=$(echo $ER1 | tr ',' ' ')
  L=$(echo $LR1 | tr ',' ' ')
fi

NUMSAMPLES=$(echo $E | wc -w)

rfq="$E $L"
index=$(index $INDEXFILE)
cfq=$(clip -t $NTHREADS $rfq)
bam=$(align -t $NTHREADS -i $index $cfq)
samstats -t $NTHREADS $E $L
sbam=$(filtersort -t $NTHREADS $bam)
samstats   -t $NTHREADS $E $L
rbam=$(dedup -t $NTHREADS $sbam)
bed=$(bam2bed -t $NTHREADS $rbam)
bg=$(count -t $NTHREADS $bed)
fbg=$(filter -t $NTHREADS $bg)

ebg=$(echo $fbg | tr ' ' '\n' | head -n $NUMSAMPLES | tr '\n' ',' | sed 's/,$//g')
lbg=$(echo $fbg | tr ' ' '\n' | tail -n $NUMSAMPLES | tr '\n' ',' | sed 's/,$//g')

log2ratio $ebg $lbg



