#!/usr/bin/env bash

usage() {
  echo "Usage: $(basename $0) [-t threads ] fastq1 [bam1 bam2 ... bamN ]" 1>&2
  echo "" 1>&2
  exit 1
}

while getopts ":t:" opt; do
  case $opt in
  t)
    NTHREADS=$OPTARG
   ;;
  \?)
   echo "Invalid option: -$OPTARG" >&2
   usage
   ;;
  [?])
   usage
   ;;
  :)
   echo "Option -$OPTARG requires an argument." >&2
   echo "" >&2
   usage
   ;;
  esac
done

if [ -z $NTHREADS ]; then
  NTHREADS=1
fi

shift $((OPTIND-1))

if [[ $# -eq 0 ]] ; then
  echo 'no bam files specified'
  exit 1
fi

INPUT=$@

samstats(){
  INPUT=$1
  # check if file exists
  if [[ ! -f $f ]]; then echo "file \"$f\" not found"; exit 1; fi
  # check input is a fastq
  if [[ $f != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
  
  BASE="$(basename $f)"
  OUTPUT=${BASE}.samstats
  
  samtools stats $INPUT > $OUTPUT
  echo $OUTPUT
}

export -f samstats

parallel --will-cite -k -j $NTHREADS "samstats {}" ::: $INPUT
